name: Compute Benchmarks

on:
  workflow_dispatch:
    inputs:
      pr_no:
        description: PR number (if 0, it'll run on the main)
        type: number
      bench_script_params:
        description: Parameters passed to script executing benchmark
        type: string
        required: false
        default: ''
      upload_report:
        description: 'Upload HTML report'
        type: boolean
        required: false
        default: false

permissions:
  contents: read
  pull-requests: write

jobs:
  manual:
    name: Compute Benchmarks
    uses: ./.github/workflows/reusable_benchmarks.yml
    with:
      pr_no: ${{ inputs.pr_no }}
      bench_script_params: ${{ inputs.bench_script_params }}
      upload_report: ${{ inputs.upload_report }}
