# Deploy documentation to GitHub Pages
name: GitHubPages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Cancel previous in-progress workflow, only the latest run is relevant
concurrency:
  group: "docs"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  DocsBuild:
    uses: ./.github/workflows/reusable_docs_build.yml
    with:
      upload: true

  DocsDeploy:
    name: Deploy docs to GitHub Pages
    needs: DocsBuild

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ${{ github.repository_owner == 'oneapi-src' && 'intel-ubuntu-22.04' || 'ubuntu-latest' }}

    steps:
    - name: Deploy the documentation to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@87c3283f01cd6fe19a0ab93a23b2f6fcba5a8e42 # v4.0.3
