name: Codespell
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      UMF_BRANCH: 
        required: true
      UMF_REPOSITORY:
        required: true
        default: https://github.com/oneapi-src/unified-memory-framework.git

permissions:
  actions: read
  checks: read
  contents: read
  pull-requests: write

jobs:
  codespell:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install codespell
        run: |
          pip install codespell

      - name: Run codespell
        run: |
          bash .github/scripts/codespell.sh
