name: Docs build

on:
  workflow_call:
    inputs:
      upload:
        description: Should HTML documentation be uploaded as artifact?
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  DocsBuild:
    name: Docs build
    runs-on: ${{ github.repository_owner == 'oneapi-src' && 'intel-ubuntu-22.04' || 'ubuntu-latest' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0

    - name: Install doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    # Latest distros do not allow global pip installation
    - name: Install Python requirements in venv
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        echo "$PATH" >> $GITHUB_PATH
        python3 -m pip install -r third_party/requirements.txt

    - name: Build the documentation
      run: |
        cmake -B build \
          -DUMF_BUILD_LEVEL_ZERO_PROVIDER=OFF \
          -DUMF_BUILD_CUDA_PROVIDER=OFF \
          -DUMF_BUILD_TESTS=OFF \
          -DUMF_BUILD_EXAMPLES=OFF \
          -DUMF_DISABLE_HWLOC=ON
        cmake --build build --target docs

    # If we upload HTML docs, we want to include benchmark results as well
    - name: Download benchmark HTML before uploading docs
      if: ${{ inputs.upload == true }}
      id: download-bench-html
      uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: umf-repo/build/benchmark_results.html
        key: benchmark-results-

    - name: Move benchmark HTML
      if: ${{ inputs.upload == true && steps.download-bench-html.outputs.cache-hit != '' }}
      run: |
        mv umf-repo/build/benchmark_results.html ${{github.workspace}}/build/docs_build/generated/html

    - name: Upload artifact
      if: ${{ inputs.upload == true }}
      uses: actions/upload-pages-artifact@0252fc4ba7626f0298f0cf00902a25c6afc77fa8 # v3.0.0
      with:
        path: build/docs_build/generated/html
