name: Test
 on: [push]
 
 jobs:
   test:
     runs-on: self-hosted
     steps:
       - name: Print Hello World
       - run: echo "Hello world"
         run: echo "Hello world and hellow new runner"
